### ISSUE TITLE
Changing host or port configs by passing them via runner arguments

### ISSUE THREAD

**Issue by olimination** [unic/ScalaWebTest#12]
I would like to be able to pass the host or port configs from outside the test so that I can run my tests for different environments.

Example in AEM:
Running tests for Author and Publish.

Solution Proposal:
As far as I have seen the ScalaTest _ConfigMap_ seems to be for such cases: http://doc.scalatest.org/3.0.0/index.html#org.scalatest.ConfigMap

**Comment by DaniRey** [comment]
Great idea!

Do you want to create a pull request? We could also organize a pair programming session to implement this. Should be doable before season holidays.

**Comment by DaniRey** [comment]
@olimination Are you still interested in this change?

**Comment by olimination** [comment]
@DaniRey Interested yes, but I'm currently struggling with my available time capacity and priorities. I leave it unassigned, and if I see any spare time, I would like to implement it. Maybe I can integrate it within a next project :)

**Comment by DaniRey** [comment]
I'm already halfway there with the implementation 😀

But I would like to have some user feedback before finishing it. I'll keep you posted about the implementation.

**Comment by DaniRey** [comment]
I tried configMap and it has two issues. 

1.  configMap is only initialized (available) when using org.scalatest.tools.Runner to run the test (usually not the case)
2. configMap would require additional indirection, because we have to delay the initialization of the webdriver until we receive the configMap

Therefore we decided to use System.getProperty and System.getenv and provide the Configurable abstraction to access the information. There is already a working implementation of this approach in https://github.com/unic/ScalaWebTest/tree/feature/scalawebtest-74-wip used to control the webdriver path.

**Comment by DaniRey** [comment]
- Merged host and loginPath/basePath into config.useBaseUri/loginConfig.useLoginUri, this makes configuration consistent (always in config object) and allows for cleaner configuration via command line arguments

- config.baseUri can be overwritten with the system.property(scalawebtest.base.uri), the environment variable (scalawebtest.base.uri or SCALAWEBTEST_BASE_URI), or the run argument (scalawebtest.base.uri)

- loginConfig.loginUri can be overwritten with the system.property(scalawebtest.login.uri), the environment variable (scalawebtest.login.uri or SCALAWEBTEST_LOGIN_URI), or the run argument (scalawebtest.login.uri)
